const char *<core::num::error::TryFromIntError as core::error::Error>::description()
{
  return aOutOfRangeInte;
}
